package asia.xiaoer.mybatis.mybatis_generate.domain;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.id
     *
     * @mbg.generated Thu Dec 22 15:09:20 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.name
     *
     * @mbg.generated Thu Dec 22 15:09:20 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.sn
     *
     * @mbg.generated Thu Dec 22 15:09:20 CST 2022
     */
    private String sn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.id
     *
     * @return the value of department.id
     *
     * @mbg.generated Thu Dec 22 15:09:20 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.id
     *
     * @param id the value for department.id
     *
     * @mbg.generated Thu Dec 22 15:09:20 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.name
     *
     * @return the value of department.name
     *
     * @mbg.generated Thu Dec 22 15:09:20 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.name
     *
     * @param name the value for department.name
     *
     * @mbg.generated Thu Dec 22 15:09:20 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.sn
     *
     * @return the value of department.sn
     *
     * @mbg.generated Thu Dec 22 15:09:20 CST 2022
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.sn
     *
     * @param sn the value for department.sn
     *
     * @mbg.generated Thu Dec 22 15:09:20 CST 2022
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }
}